rename docs/ --> doc/ (#1390)
* rename docs/ --> doc/

* do not change doc website

* implement @MatthewFlamm finds

* final docs/ to doc/

* fix duplicate rst

* remove external_examples

* Two stale references to docs/ in docs comments

* Update setup.cfg

Co-authored-by: Andras Deak <adeak@users.noreply.github.com>

* update .gitignore and pipelines for merge

* Update azure-pipelines.yml

Co-authored-by: Andras Deak <adeak@users.noreply.github.com>

Co-authored-by: Andras Deak <deak.andris@gmail.com>
Co-authored-by: Andras Deak <adeak@users.noreply.github.com>

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -240,22 +240,22 @@ jobs:
   - task: Cache@2
     inputs:
       key: 'PYVISTA_DOC_EXAMPLES_CACHE | "$(PYVISTA_VERSION)"'
-      path: '$(Build.SourcesDirectory)/docs/examples'
+      path: '$(Build.SourcesDirectory)/doc/examples'
     displayName: Build pyvista doc examples cache
 
   # run this twice since VTK9 fails to close render windows
   - script: |
-      make -C docs phtml || true  # will fail on VTK9
-      make -C docs phtml -b coverage SPHINXOPTS="-W"
-      cat docs/_build/coverage/python.txt
+      make -C doc phtml || true  # will fail on VTK9
+      make -C doc phtml -b coverage SPHINXOPTS="-W"
+      cat doc/_build/coverage/python.txt
     displayName: 'Build documentation'
 
   # Push example notebooks to pyvista-examples
   - script: |
       pip install cookiecutter
-      cookiecutter -f --no-input --config-file ./docs/pyvista-binder-config.yml -o .. https://github.com/pyvista/cookiecutter-pyvista-binder.git;
+      cookiecutter -f --no-input --config-file ./doc/pyvista-binder-config.yml -o .. https://github.com/pyvista/cookiecutter-pyvista-binder.git;
       rm -rf ../pyvista-examples/notebooks/
-      cd docs
+      cd doc
       find examples -type f -name '*.ipynb' | cpio -p -d -v ../../pyvista-examples/
       cd ../../pyvista-examples/
       git init
@@ -273,9 +273,9 @@ jobs:
   # Push example notebooks to pyvista-examples develop branch
   - script: |
       pip install cookiecutter
-      cookiecutter -f --no-input --config-file ./docs/pyvista-binder-config.yml -o .. https://github.com/pyvista/cookiecutter-pyvista-binder.git;
+      cookiecutter -f --no-input --config-file ./doc/pyvista-binder-config.yml -o .. https://github.com/pyvista/cookiecutter-pyvista-binder.git;
       rm -rf ../pyvista-examples/notebooks/
-      cd docs
+      cd doc
       find examples -type f -name '*.ipynb' | cpio -p -d -v ../../pyvista-examples/
       cd ../../pyvista-examples/
       git init
@@ -298,9 +298,9 @@ jobs:
       git gc --prune=now
       git remote prune origin
       rm -rf *
-      cp -r $BUILD_SOURCESDIRECTORY/docs/_build/html/* .
-      cp $BUILD_SOURCESDIRECTORY/docs/README.md .
-      cp $BUILD_SOURCESDIRECTORY/docs/ads.txt .
+      cp -r $BUILD_SOURCESDIRECTORY/doc/_build/html/* .
+      cp $BUILD_SOURCESDIRECTORY/doc/README.md .
+      cp $BUILD_SOURCESDIRECTORY/doc/ads.txt .
       touch .nojekyll
       echo "docs.pyvista.org" >> CNAME
       git add .
@@ -317,9 +317,9 @@ jobs:
       cd pyvista-docs-dev
       git init
       git checkout -b gh-pages
-      cp -r $BUILD_SOURCESDIRECTORY/docs/_build/html/* .
-      cp $BUILD_SOURCESDIRECTORY/docs/README.md .
-      cp $BUILD_SOURCESDIRECTORY/docs/ads.txt .
+      cp -r $BUILD_SOURCESDIRECTORY/doc/_build/html/* .
+      cp $BUILD_SOURCESDIRECTORY/doc/README.md .
+      cp $BUILD_SOURCESDIRECTORY/doc/ads.txt .
       touch .nojekyll
       echo "dev.pyvista.org" >> CNAME
       git add .
